# Generated by Django 3.2 on 2024-09-22 23:52

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=200)),
                ('description', models.CharField(db_column='description', max_length=200)),
                ('completed', models.BooleanField(db_column='completed', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed_at', null=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
